spring:
  profiles:
    active: dev
#  devtools:
#    livereload:
#      port: 8066
  thymeleaf:
      cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #解决配置了swagger启动就会报空指针异常问题（改变路径匹配模式）

server:
  port: 9090
#  servlet:
#    context-path: /konan

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #配置日志

  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1     #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)